# Generated by Django 6.0.5 on 2026-05-13 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Номер телефона содержит 10–12 цифр и может начинаться с .', regex='^\\+?\\d{10,12}$')], verbose_name='Телефон'),
        ),
    ]
